name: 🚀 Deploy website on push

on:
  push:
    branches:
      - main

jobs:
  web-deploy:
    name: 🎉 Deploy static files
    runs-on: ubuntu-latest

    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v2

      - name: 📂 Upload files to FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.0
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./
          server-dir: /public_html/api/
          protocol: ftps
          port: 21


# name: 🚀 Deploy website on push
# on: 
#   push:
#     branches:
#       - main
# jobs:
#   web-deploy:
#     name: 🎉 Deploy
#     runs-on: ubuntu-latest
#     steps:
#       - name: 🚚 Get latest code
#         uses: actions/checkout@v2
      
#       - name: 🔧 Setup Node.js
#         uses: actions/setup-node@v2
#         with:
#           node-version: '18'
      
#       - name: 📦 Install dependencies
#         run: npm ci
      
#       - name: 🏗️ Build project
#         run: npm run build
      
#       - name: 📂 Sync build files
#         uses: SamKirkland/FTP-Deploy-Action@v4.3.0-beta
#         with:
#           server: ${{ secrets.FTP_SERVER }}
#           username: ${{ secrets.FTP_USERNAME }}
#           password: ${{ secrets.FTP_PASSWORD }}
#           local-dir: ./dist/
#           server-dir: /api
#           protocol: ftps
#           port: 21